name: simulainvest
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0    # Permite carregar variáveis de ambiente a partir de um arquivo .env
  http: ^0.13.6             # Permite fazer requisições HTTP e acessar APIs externas
  intl: ^0.19.0             # Formatação de datas e números internacionalizados
  provider: ^6.0.0          # Gerenciamento de estado e injeção de dependências

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
